language: elixir

elixir:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
otp_release:
  - 19.3
  - 20.3
  - 21.0
  - 22.0
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 21.0
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.9
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 20.3
sudo: false

script:
  - elixir --version | grep -q '^Elixir 1\.3\|Elixir 1\.4\|Elixir 1\.5' || mix format --check-formatted
  - mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
